



Traceback (most recent call last):
  File "./u.py", line 8, in <module>
    velocity.GetDiagBundle(IP=wc.argv_dict['IP'], user=wc.argv_dict['user'], pword=wc.argv_dict['pass'])
  File "/home/adrian/shared_libs/velocity.py", line 20, in GetDiagBundle
    wc.jd(json.loads(wc.REST_GET('https://' + IP + '/configure/diag-bundle-with-db.zip?mode=save_diag_with_db', user=user, pword=pword)))
  File "/home/adrian/shared_libs/wcommon.py", line 959, in REST_GET
    return(json.dumps(data))
  File "/home/adrian/.pyenv/versions/3.6.8/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/adrian/.pyenv/versions/3.6.8/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/adrian/.pyenv/versions/3.6.8/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/adrian/.pyenv/versions/3.6.8/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
